import java.util.Scanner;

class Main {

    public static double addition(double a, double b) {
            return a + b;
                }

                    public static double subtraction(double a, double b) {
                            return a - b;
                                }

                                    public static double multiplication(double a, double b) {
                                            return a * b;
                                                }

                                                    public static double division(double a, double b) {
                                                            if (b == 0) {
                                                                        System.out.println("Cannot divide by zero.");
                                                                                    return 0;
                                                                                            }
                                                                                                    return a / b;
                                                                                                        }

                                                                                                            public static void main(String[] args) {


                                                                                                                    Scanner scanner = new Scanner(System.in);

                                                                                                                            int choice;

                                                                                                                                    do {
                                                                                                                                                System.out.println("\n===== JAVA CONSOLE CALCULATOR =====");
                                                                                                                                                            System.out.println("1. Addition");
                                                                                                                                                                        System.out.println("2. Subtraction");
                                                                                                                                                                                    System.out.println("3. Multiplication");
                                                                                                                                                                                                System.out.println("4. Division");
                                                                                                                                                                                                            System.out.println("5. Exit");

                                                                                                                                                                                                                        System.out.print("Enter your choice: ");
                                                                                                                                                                                                                                    choice = scanner.nextInt();

                                                                                                                                                                                                                                                if (choice >= 1 && choice <= 4) {

                                                                                                                                                                                                                                                                System.out.print("Enter first number: ");
                                                                                                                                                                                                                                                                                double num1 = scanner.nextDouble();

                                                                                                                                                                                                                                                                                                System.out.print("Enter second number: ");
                                                                                                                                                                                                                                                                                                                double num2 = scanner.nextDouble();

                                                                                                                                                                                                                                                                                                                                switch (choice) {
                                                                                                                                                                                                                                                                                                                                                    case 1:
                                                                                                                                                                                                                                                                                                                                                                            System.out.println("Result = " + addition(num1, num2));
                                                                                                                                                                                                                                                                                                                                                                                                    break;

                                                                                                                                                                                                                                                                                                                                                                                                                        case 2:
                                                                                                                                                                                                                                                                                                                                                                                                                                                System.out.println("Result = " + subtraction(num1, num2));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            case 3:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.println("Result = " + multiplication(num1, num2));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 4:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println("Result = " + division(num1, num2));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else if (choice == 5) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println("Thank you for using the calculator.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println("Invalid choice. Please try again.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } while (choice != 5);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    scanner.close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }